#companies
[
    {
        "name": "GreenThumb Agriculture",
        "abn": 22345678901,
        "size": 10,
        "industry": "agriculture",
        "logo": "https://picsum.photos/201",
        "about": "GreenThumb Agriculture is revolutionizing the way small-scale farmers connect with resources and markets. We provide a digital platform that allows farmers to access the best tools, techniques, and advice for maximizing crop yield. Our mission is to support sustainable farming practices by giving farmers the knowledge and tools they need to succeed in a rapidly changing industry.",
        "website_link": "https://greenthumbagriculture.com.au",
        "admin_email": "contact@greenthumbagriculture.com.au",
        "hashed_password": "abcd1234",
        "facebook_link": "https://facebook.com/greenthumbagriculture",
        "linkedin_link": "https://linkedin.com/greenthumbagriculture",
        "instagram_link": "https://instagram.com/greenthumbagriculture"
    },
    {
        "name": "BuildSmart Solutions",
        "abn": 22345678902,
        "size": 25,
        "industry": "construction",
        "logo": "https://picsum.photos/202",
        "about": "BuildSmart Solutions is a leading innovator in the construction industry, offering advanced project management tools that streamline the building process from start to finish. Our platform integrates with existing systems to provide real-time data and analytics, helping construction managers stay on top of timelines, budgets, and resources. We are committed to making construction projects more efficient and cost-effective.",
        "website_link": "https://buildsmartsolutions.com.au",
        "admin_email": "info@buildsmartsolutions.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/buildsmartsolutions",
        "linkedin_link": "https://linkedin.com/buildsmartsolutions",
        "instagram_link": "https://instagram.com/buildsmartsolutions"
    },
    {
        "name": "EduPath Learning",
        "abn": 22345678903,
        "size": 50,
        "industry": "education",
        "logo": "https://picsum.photos/203",
        "about": "EduPath Learning is an online education platform that offers personalized learning experiences for students of all ages. Our platform leverages artificial intelligence to create tailored learning paths, ensuring each student can learn at their own pace. We partner with top educators and institutions to provide high-quality courses and resources that help students achieve their academic goals.",
        "website_link": "https://edupathlearning.com.au",
        "admin_email": "support@edupathlearning.com.au",
        "hashed_password": "1234abcd",
        "facebook_link": "https://facebook.com/edupathlearning",
        "linkedin_link": "https://linkedin.com/edupathlearning",
        "instagram_link": "https://instagram.com/edupathlearning"
    },
    {
        "name": "MediTech Innovations",
        "abn": 22345678904,
        "size": 150,
        "industry": "health",
        "logo": "https://picsum.photos/204",
        "about": "MediTech Innovations is at the forefront of healthcare technology, developing cutting-edge solutions that improve patient care and streamline healthcare operations. Our products range from advanced diagnostic tools to telemedicine platforms, all designed to enhance the efficiency and effectiveness of healthcare delivery. We are dedicated to creating technologies that empower healthcare providers and improve patient outcomes.",
        "website_link": "https://meditechinnovations.com.au",
        "admin_email": "contact@meditechinnovations.com.au",
        "hashed_password": "abcd1234",
        "facebook_link": "https://facebook.com/meditechinnovations",
        "linkedin_link": "https://linkedin.com/meditechinnovations",
        "instagram_link": "https://instagram.com/meditechinnovations"
    },
    {
        "name": "FarmFresh Markets",
        "abn": 22345678905,
        "size": 30,
        "industry": "agriculture",
        "logo": "https://picsum.photos/205",
        "about": "FarmFresh Markets connects local farmers with consumers who want fresh, organic produce. Our platform allows users to browse and purchase directly from farms in their area, ensuring that they get the freshest produce possible. We are committed to supporting local agriculture and promoting sustainable farming practices through our innovative marketplace.",
        "website_link": "https://farmfreshmarkets.com.au",
        "admin_email": "info@farmfreshmarkets.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/farmfreshmarkets",
        "linkedin_link": "https://linkedin.com/farmfreshmarkets",
        "instagram_link": "https://instagram.com/farmfreshmarkets"
    },
    {
        "name": "LegalEase",
        "abn": 22345678906,
        "size": 15,
        "industry": "legal",
        "logo": "https://picsum.photos/206",
        "about": "LegalEase is a legal tech startup that simplifies the legal process for individuals and small businesses. Our platform provides easy access to legal documents, contract templates, and attorney consultations. We aim to make legal services more affordable and accessible by leveraging technology to eliminate the complexities traditionally associated with legal processes.",
        "website_link": "https://legalease.com.au",
        "admin_email": "contact@legalease.com.au",
        "hashed_password": "1234abcd",
        "facebook_link": "https://facebook.com/legalease",
        "linkedin_link": "https://linkedin.com/legalease",
        "instagram_link": "https://instagram.com/legalease"
    },
    {
        "name": "UrbanGreen Construction",
        "abn": 22345678907,
        "size": 100,
        "industry": "construction",
        "logo": "https://picsum.photos/207",
        "about": "UrbanGreen Construction is committed to sustainable building practices, offering green construction solutions for urban development projects. We specialize in eco-friendly materials and energy-efficient designs, helping clients build structures that are not only durable but also environmentally responsible. Our goal is to lead the way in sustainable construction, ensuring a better future for our cities and our planet.",
        "website_link": "https://urbangreenconstruction.com.au",
        "admin_email": "info@urbangreenconstruction.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/urbangreenconstruction",
        "linkedin_link": "https://linkedin.com/urbangreenconstruction",
        "instagram_link": "https://instagram.com/urbangreenconstruction"
    },
    {
        "name": "MediaMinds",
        "abn": 22345678908,
        "size": 80,
        "industry": "media",
        "logo": "https://picsum.photos/208",
        "about": "MediaMinds is a content creation and marketing agency that helps businesses tell their stories through engaging and impactful media. We offer a wide range of services, including video production, social media management, and digital marketing strategies. Our team of creative professionals works closely with clients to develop customized solutions that resonate with their target audience.",
        "website_link": "https://mediaminds.com.au",
        "admin_email": "contact@mediaminds.com.au",
        "hashed_password": "abcd1234",
        "facebook_link": "https://facebook.com/mediaminds",
        "linkedin_link": "https://linkedin.com/mediaminds",
        "instagram_link": "https://instagram.com/mediaminds"
    },
    {
        "name": "HealthWave",
        "abn": 22345678909,
        "size": 60,
        "industry": "health",
        "logo": "https://picsum.photos/209",
        "about": "HealthWave is transforming the healthcare industry by providing a comprehensive telehealth platform that connects patients with healthcare providers. Our platform offers virtual consultations, remote monitoring, and access to medical records, making healthcare more convenient and accessible for patients. We are dedicated to improving healthcare delivery through innovative technology and patient-centered solutions.",
        "website_link": "https://healthwave.com.au",
        "admin_email": "info@healthwave.com.au",
        "hashed_password": "1234abcd",
        "facebook_link": "https://facebook.com/healthwave",
        "linkedin_link": "https://linkedin.com/healthwave",
        "instagram_link": "https://instagram.com/healthwave"
    },
    {
        "name": "MindfulTech",
        "abn": 22345678910,
        "size": 40,
        "industry": "technology",
        "logo": "https://picsum.photos/210",
        "about": "MindfulTech is a mental wellness platform that combines technology with mindfulness practices to help users manage stress and improve their overall well-being. Our app offers guided meditations, mood tracking, and personalized wellness plans, all designed to fit into a busy lifestyle. We believe that mental health is just as important as physical health, and we are committed to making mindfulness accessible to everyone.",
        "website_link": "https://mindfultech.com.au",
        "admin_email": "support@mindfultech.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/mindfultech",
        "linkedin_link": "https://linkedin.com/mindfultech",
        "instagram_link": "https://instagram.com/mindfultech"
    },
    {
        "name": "AgroMinds",
        "abn": 22345678911,
        "size": 120,
        "industry": "agriculture",
        "logo": "https://picsum.photos/211",
        "about": "AgroMinds is an agricultural technology company that provides data-driven solutions to improve crop management and yield. Our platform uses advanced analytics and machine learning to help farmers make informed decisions about planting, irrigation, and fertilization. We aim to increase agricultural productivity while promoting sustainable farming practices that protect the environment.",
        "website_link": "https://agrominds.com.au",
        "admin_email": "contact@agrominds.com.au",
        "hashed_password": "abcd1234",
        "facebook_link": "https://facebook.com/agrominds",
        "linkedin_link": "https://linkedin.com/agrominds",
        "instagram_link": "https://instagram.com/agrominds"
    },
    {
        "name": "SmartBuild Innovations",
        "abn": 22345678912,
        "size": 200,
        "industry": "construction",
        "logo": "https://picsum.photos/212",
        "about": "SmartBuild Innovations is a construction technology company that develops smart building systems to enhance the efficiency and sustainability of construction projects. Our products include automated project management tools, energy-efficient materials, and smart home integration solutions. We are dedicated to transforming the construction industry through innovation and technology.",
        "website_link": "https://smartbuildinnovations.com.au",
        "admin_email": "info@smartbuildinnovations.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/smartbuildinnovations",
        "linkedin_link": "https://linkedin.com/smartbuildinnovations",
        "instagram_link": "https://instagram.com/smartbuildinnovations"
    },
    {
        "name": "EduNext",
        "abn": 22345678913,
        "size": 35,
        "industry": "education",
        "logo": "https://picsum.photos/213",
        "about": "EduNext is a next-generation online learning platform that provides interactive and personalized education experiences for students. Our platform uses AI-driven tools to assess student progress and adapt lessons to their individual needs. We partner with top educators and institutions to offer a wide range of courses that cater to different learning styles and goals.",
        "website_link": "https://edunext.com.au",
        "admin_email": "support@edunext.com.au",
        "hashed_password": "1234abcd",
        "facebook_link": "https://facebook.com/edunext",
        "linkedin_link": "https://linkedin.com/edunext",
        "instagram_link": "https://instagram.com/edunext"
    },
    {
        "name": "HealthyBites",
        "abn": 22345678914,
        "size": 45,
        "industry": "hospitality",
        "logo": "https://picsum.photos/214",
        "about": "HealthyBites is a food delivery service that focuses on providing nutritious and balanced meals to health-conscious consumers. Our menu is crafted by nutritionists and chefs to ensure that every meal is not only delicious but also good for you. We cater to a variety of dietary needs, including vegan, gluten-free, and low-carb options, making it easy for everyone to eat healthy.",
        "website_link": "https://healthybites.com.au",
        "admin_email": "info@healthybites.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/healthybites",
        "linkedin_link": "https://linkedin.com/healthybites",
        "instagram_link": "https://instagram.com/healthybites"
    },
    {
        "name": "LawConnect",
        "abn": 22345678915,
        "size": 12,
        "industry": "legal",
        "logo": "https://picsum.photos/215",
        "about": "LawConnect is a legal services platform that connects clients with lawyers who specialize in their specific legal needs. Whether it's drafting a contract, resolving a dispute, or navigating complex regulations, LawConnect makes it easy to find the right legal expert. Our platform offers transparent pricing and reviews, so clients can make informed decisions when choosing legal representation.",
        "website_link": "https://lawconnect.com.au",
        "admin_email": "contact@lawconnect.com.au",
        "hashed_password": "1234abcd",
        "facebook_link": "https://facebook.com/lawconnect",
        "linkedin_link": "https://linkedin.com/lawconnect",
        "instagram_link": "https://instagram.com/lawconnect"
    },
    {
        "name": "AgriSmart",
        "abn": 22345678916,
        "size": 90,
        "industry": "agriculture",
        "logo": "https://picsum.photos/216",
        "about": "AgriSmart is an agtech company that helps farmers optimize their operations through advanced technology. Our platform offers tools for precision farming, crop monitoring, and farm management, allowing farmers to make data-driven decisions that improve efficiency and profitability. We are committed to advancing the agricultural industry through innovation and sustainability.",
        "website_link": "https://agrismart.com.au",
        "admin_email": "info@agrismart.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/agrismart",
        "linkedin_link": "https://linkedin.com/agrismart",
        "instagram_link": "https://instagram.com/agrismart"
    },
    {
        "name": "MediaLink",
        "abn": 22345678917,
        "size": 70,
        "industry": "media",
        "logo": "https://picsum.photos/217",
        "about": "MediaLink is a digital media agency that specializes in connecting brands with their target audience through innovative marketing strategies. We offer services such as content creation, social media management, and influencer marketing. Our goal is to help brands build a strong online presence and engage with their customers in meaningful ways.",
        "website_link": "https://medialink.com.au",
        "admin_email": "contact@medialink.com.au",
        "hashed_password": "1234abcd",
        "facebook_link": "https://facebook.com/medialink",
        "linkedin_link": "https://linkedin.com/medialink",
        "instagram_link": "https://instagram.com/medialink"
    },
    {
        "name": "MineSafe",
        "abn": 22345678918,
        "size": 130,
        "industry": "mining",
        "logo": "https://picsum.photos/218",
        "about": "MineSafe is a mining technology company focused on improving safety and efficiency in mining operations. We develop advanced monitoring systems that provide real-time data on environmental conditions, equipment performance, and worker safety. Our solutions help mining companies reduce risks, improve operational efficiency, and ensure compliance with industry regulations.",
        "website_link": "https://minesafe.com.au",
        "admin_email": "info@minesafe.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/minesafe",
        "linkedin_link": "https://linkedin.com/minesafe",
        "instagram_link": "https://instagram.com/minesafe"
    },
    {
        "name": "HealthConnect",
        "abn": 22345678919,
        "size": 55,
        "industry": "health",
        "logo": "https://picsum.photos/219",
        "about": "HealthConnect is a healthcare platform that integrates patient data across multiple providers, ensuring that healthcare professionals have access to comprehensive and up-to-date information. Our platform improves coordination of care, reduces errors, and enhances the overall patient experience. We are committed to making healthcare more connected and efficient.",
        "website_link": "https://healthconnect.com.au",
        "admin_email": "contact@healthconnect.com.au",
        "hashed_password": "abcd1234",
        "facebook_link": "https://facebook.com/healthconnect",
        "linkedin_link": "https://linkedin.com/healthconnect",
        "instagram_link": "https://instagram.com/healthconnect"
    },
    {
        "name": "EduLink",
        "abn": 22345678920,
        "size": 20,
        "industry": "education",
        "logo": "https://picsum.photos/220",
        "about": "EduLink is an educational technology company that provides tools and resources for online learning and collaboration. Our platform offers a range of features, including virtual classrooms, interactive course materials, and collaborative project tools. We are dedicated to enhancing the learning experience by making education more accessible, engaging, and effective.",
        "website_link": "https://edulink.com.au",
        "admin_email": "support@edulink.com.au",
        "hashed_password": "abcd5678",
        "facebook_link": "https://facebook.com/edulink",
        "linkedin_link": "https://linkedin.com/edulink",
        "instagram_link": "https://instagram.com/edulink"
    }
]


#jobs
[
    {
        "title": "Software Engineer",
        "salary": 120000,
        "department": "technology",
        "role_description": "GreenThumb Agriculture is seeking a skilled Software Engineer to join our growing technology team. In this role, you'll be responsible for developing and maintaining our core platform that helps farmers optimize their operations. The ideal candidate should be proficient in Python and JavaScript, with experience in cloud-based environments. You'll work closely with our data scientists and agricultural experts to build scalable solutions that make a real impact in the field.",
        "experience": "3 years in Python and JavaScript development",
        "application_link": "https://greenthumbagriculture.com.au/apply/software-engineer",
        "location": "nsw",
        "location-specific": "wollongong",
        "job_type": "full-time",
        "closing_date": "2024-11-15"
    },
    {
        "title": "Marketing Coordinator",
        "salary": 65000,
        "department": "marketing",
        "role_description": "GreenThumb Agriculture is looking for a creative Marketing Coordinator to help drive our marketing efforts. You'll be responsible for creating content, managing social media, and coordinating marketing campaigns. The ideal candidate should have experience with digital marketing tools, including Google Analytics and social media platforms, and a passion for sustainable agriculture.",
        "experience": "2 years in digital marketing",
        "application_link": "Email careers@greenthumbagriculture.com.au",
        "location": "vic",
        "location-specific": "geelong",
        "job_type": "part-time"
    },
    {
        "title": "Operations Manager",
        "salary": 85000,
        "department": "operations",
        "role_description": "As an Operations Manager at GreenThumb Agriculture, you will oversee the day-to-day operations of our business. This role requires strong organizational skills and the ability to manage logistics, supply chains, and team performance. You will be a key player in ensuring that our operations run smoothly and efficiently.",
        "experience": "5 years in operations management",
        "application_link": "https://greenthumbagriculture.com.au/apply/operations-manager",
        "location": "qld",
        "location-specific": "toowoomba",
        "job_type": "full-time",
        "closing_date": "2024-10-31"
    },
    {
        "title": "Project Manager",
        "salary": 95000,
        "department": "operations",
        "role_description": "BuildSmart Solutions is seeking an experienced Project Manager to lead our construction projects. You will be responsible for overseeing project timelines, budgets, and quality control. The ideal candidate has a background in construction management and is familiar with project management software like MS Project or Primavera.",
        "experience": "4 years in construction project management",
        "application_link": "Email jobs@buildsmartsolutions.com.au",
        "location": "sa",
        "location-specific": "port adelaide",
        "job_type": "full-time",
        "closing_date": "2024-12-01"
    },
    {
        "title": "Full Stack Developer",
        "salary": 130000,
        "department": "technology",
        "role_description": "Join BuildSmart Solutions as a Full Stack Developer and play a crucial role in developing our project management platform. You'll work with a dynamic team to design, code, and deploy scalable web applications. Proficiency in React and Node.js is essential, and experience with cloud services such as AWS or Azure is highly desirable.",
        "experience": "3 years in React and Node.js development",
        "application_link": "https://buildsmartsolutions.com.au/apply/fullstack-developer",
        "location": "nsw-sydney",
        "job_type": "full-time"
    },
    {
        "title": "Finance Manager",
        "salary": 100000,
        "department": "finance",
        "role_description": "BuildSmart Solutions is seeking a Finance Manager to oversee our financial operations, including budgeting, forecasting, and financial reporting. The ideal candidate will have a strong understanding of financial regulations and accounting principles. Experience with financial software like Xero or MYOB is required.",
        "experience": "5 years in finance management",
        "application_link": "Email jobs@buildsmartsolutions.com.au",
        "location": "vic-melbourne",
        "job_type": "full-time"
    },
    {
        "title": "Software Engineer",
        "salary": 110000,
        "department": "technology",
        "role_description": "EduPath Learning is looking for a talented Software Engineer to help build and enhance our online learning platform. You will work closely with our product team to develop new features and improve existing ones. The ideal candidate should be proficient in Ruby on Rails and have experience with frontend frameworks like Angular or React.",
        "experience": "3 years in Ruby on Rails development",
        "application_link": "https://edupathlearning.com.au/apply/software-engineer",
        "location": "remote",
        "job_type": "full-time",
        "closing_date": "2024-10-20"
    },
    {
        "title": "Instructional Designer",
        "salary": 85000,
        "department": "design",
        "role_description": "EduPath Learning is looking for an Instructional Designer to create engaging and effective learning materials for our online courses. You will work closely with subject matter experts to develop content that meets the needs of our diverse student base. Experience with e-learning software such as Articulate or Adobe Captivate is a must.",
        "experience": "2 years in instructional design",
        "application_link": "Email careers@edupathlearning.com.au",
        "location": "vic",
        "location-specific": "bendigo",
        "job_type": "full-time"
    },
    {
        "title": "Front-End Developer",
        "salary": 95000,
        "department": "technology",
        "role_description": "TechLink Solutions is seeking a Front-End Developer to join our team. In this role, you will be responsible for developing the user interface of our web applications using HTML, CSS, and JavaScript. Experience with Angular or React is preferred. You'll work closely with our UX designers to create responsive and intuitive user experiences.",
        "experience": "2 years in front-end development",
        "application_link": "https://techlinksolutions.com.au/apply/frontend-developer",
        "location": "wa-perth",
        "job_type": "full-time",
        "closing_date": "2024-12-15"
    },
    {
        "title": "Backend Developer",
        "salary": 115000,
        "department": "technology",
        "role_description": "TechLink Solutions is hiring a Backend Developer to work on our cloud-based platforms. You will be responsible for server-side logic, database management, and API integration. Proficiency in Node.js and SQL databases is required, and experience with Docker or Kubernetes is a plus.",
        "experience": "3 years in backend development",
        "application_link": "Email hr@techlinksolutions.com.au",
        "location": "qld-brisbane",
        "job_type": "full-time"
    },
    {
        "title": "Data Analyst",
        "salary": 80000,
        "department": "technology",
        "role_description": "Data-driven decisions are at the core of our business at TechLink Solutions. We are looking for a Data Analyst to collect, analyze, and interpret complex datasets. The ideal candidate should be proficient in SQL, Python, and data visualization tools like Tableau or Power BI. You'll provide insights that will help shape our product strategies.",
        "experience": "2 years in data analysis",
        "application_link": "https://techlinksolutions.com.au/apply/data-analyst",
        "location": "remote",
        "job_type": "full-time"
    }
]

#more jobs
[
    {
        "title": "Product Designer",
        "salary": 90000,
        "department": "design",
        "role_description": "EcoBuild is searching for a Product Designer who is passionate about sustainable architecture. In this role, you will be responsible for designing user-centric products that meet the needs of our clients and contribute to environmental sustainability. The ideal candidate should have experience with CAD software and a strong portfolio demonstrating their design skills.",
        "experience": "3 years in product design",
        "application_link": "https://ecobuild.com.au/apply/product-designer",
        "location": "vic",
        "location-specific": "ballarat",
        "job_type": "full-time",
        "closing_date": "2024-11-30"
    },
    {
        "title": "Marketing Specialist",
        "salary": 75000,
        "department": "marketing",
        "role_description": "EcoBuild is looking for a Marketing Specialist to lead our marketing efforts and increase brand awareness. You will be responsible for developing marketing strategies, managing campaigns, and analyzing their performance. Experience with digital marketing platforms like Google Ads and Facebook Ads is essential.",
        "experience": "2 years in marketing",
        "application_link": "Email hr@ecobuild.com.au",
        "location": "sa-adelaide",
        "job_type": "full-time"
    },
    {
        "title": "Sustainability Consultant",
        "salary": 85000,
        "department": "operations",
        "role_description": "Join EcoBuild as a Sustainability Consultant and help our clients achieve their sustainability goals. You will work with various stakeholders to implement eco-friendly practices and ensure compliance with environmental regulations. A background in environmental science or sustainability is highly preferred.",
        "experience": "3 years in sustainability consulting",
        "application_link": "https://ecobuild.com.au/apply/sustainability-consultant",
        "location": "nsw-sydney",
        "job_type": "full-time"
    },
    {
        "title": "UX/UI Designer",
        "salary": 95000,
        "department": "design",
        "role_description": "HealthSync Solutions is looking for a UX/UI Designer to join our team and help create intuitive and user-friendly healthcare applications. You will work closely with our product and development teams to design interfaces that improve patient engagement and experience. The ideal candidate should have experience with Figma or Adobe XD.",
        "experience": "3 years in UX/UI design",
        "application_link": "Email careers@healthsyncsolutions.com.au",
        "location": "vic-melbourne",
        "job_type": "full-time",
        "closing_date": "2024-12-05"
    },
    {
        "title": "Mobile App Developer",
        "salary": 120000,
        "department": "technology",
        "role_description": "HealthSync Solutions is seeking a Mobile App Developer to work on our suite of healthcare applications. You will be responsible for developing and maintaining mobile apps for both iOS and Android platforms. Proficiency in Swift for iOS and Kotlin for Android is required.",
        "experience": "3 years in mobile app development",
        "application_link": "https://healthsyncsolutions.com.au/apply/mobile-developer",
        "location": "remote",
        "job_type": "full-time"
    },
    {
        "title": "Data Scientist",
        "salary": 110000,
        "department": "technology",
        "role_description": "HealthSync Solutions is hiring a Data Scientist to help us analyze and interpret large datasets to improve patient outcomes. The ideal candidate should have experience with machine learning algorithms and be proficient in Python and R. You will work closely with our healthcare professionals to develop data-driven insights.",
        "experience": "3 years in data science",
        "application_link": "https://healthsyncsolutions.com.au/apply/data-scientist",
        "location": "qld-brisbane",
        "job_type": "full-time"
    },
    {
        "title": "Sales Executive",
        "salary": 75000,
        "department": "marketing",
        "role_description": "HospitalityNow is looking for a Sales Executive to drive our sales efforts and expand our client base in the hospitality industry. You will be responsible for identifying new business opportunities, managing client relationships, and closing deals. The ideal candidate should have a proven track record in sales and a deep understanding of the hospitality sector.",
        "experience": "3 years in sales",
        "application_link": "https://hospitalitynow.com.au/apply/sales-executive",
        "location": "nsw-sydney",
        "job_type": "full-time",
        "closing_date": "2024-11-20"
    },
    {
        "title": "Customer Support Specialist",
        "salary": 60000,
        "department": "operations",
        "role_description": "HospitalityNow is hiring a Customer Support Specialist to assist our clients with any issues they may encounter while using our platform. The ideal candidate should have excellent communication skills, be patient, and have experience in customer service, preferably in the hospitality industry.",
        "experience": "2 years in customer support",
        "application_link": "Email careers@hospitalitynow.com.au",
        "location": "wa-perth",
        "job_type": "full-time"
    },
    {
        "title": "Graphic Designer",
        "salary": 70000,
        "department": "design",
        "role_description": "At HospitalityNow, we are seeking a Graphic Designer to create visually appealing content for our marketing campaigns. You will be responsible for designing promotional materials, website graphics, and social media posts. Proficiency in Adobe Creative Suite is essential.",
        "experience": "3 years in graphic design",
        "application_link": "Email careers@hospitalitynow.com.au",
        "location": "remote",
        "job_type": "freelance"
    },
    {
        "title": "Legal Counsel",
        "salary": 120000,
        "department": "co-founder",
        "role_description": "LegalEase is seeking a Legal Counsel to join our founding team. In this role, you will be responsible for providing legal advice on a wide range of issues, including contracts, compliance, and intellectual property. The ideal candidate should have experience working in a startup environment and be comfortable taking on a leadership role.",
        "experience": "5 years in legal practice",
        "application_link": "https://legalease.com.au/apply/legal-counsel",
        "location": "vic-melbourne",
        "job_type": "full-time",
        "closing_date": "2024-11-10"
    },
    {
        "title": "Junior Lawyer",
        "salary": 80000,
        "department": "legal",
        "role_description": "LegalEase is hiring a Junior Lawyer to support our legal team in handling various legal tasks. You will assist in drafting contracts, conducting legal research, and ensuring compliance with regulations. The ideal candidate should be detail-oriented and have a strong understanding of corporate law.",
        "experience": "2 years in corporate law",
        "application_link": "Email hr@legalease.com.au",
        "location": "nsw",
        "location-specific": "wollongong",
        "job_type": "full-time"
    },
    {
        "title": "Legal Researcher",
        "salary": 60000,
        "department": "legal",
        "role_description": "LegalEase is looking for a Legal Researcher to join our team. In this role, you will be responsible for researching and analyzing legal issues, drafting reports, and supporting our lawyers in case preparation. The ideal candidate should have strong research skills and be familiar with legal databases.",
        "experience": "1 year in legal research",
        "application_link": "https://legalease.com.au/apply/legal-researcher",
        "location": "sa-adelaide",
        "job_type": "part-time"
    },
    {
        "title": "Business Development Manager",
        "salary": 95000,
        "department": "marketing",
        "role_description": "MediaWave is looking for a Business Development Manager to help expand our media and advertising services. You will be responsible for identifying potential clients, developing relationships, and negotiating contracts. A background in media sales and a proven track record in business development are essential.",
        "experience": "4 years in business development",
        "application_link": "https://mediawave.com.au/apply/business-development-manager",
        "location": "qld-brisbane",
        "job_type": "full-time",
        "closing_date": "2024-11-25"
    },
    {
        "title": "Social Media Manager",
        "salary": 70000,
        "department": "marketing",
        "role_description": "MediaWave is hiring a Social Media Manager to oversee our social media presence. In this role, you will be responsible for creating and executing social media strategies, managing content, and engaging with our audience. Experience with social media management tools like Hootsuite or Buffer is preferred.",
        "experience": "3 years in social media management",
        "application_link": "Email careers@mediawave.com.au",
        "location": "remote",
        "job_type": "full-time"
    },
    {
        "title": "Content Writer",
        "salary": 60000,
        "department": "marketing",
        "role_description": "MediaWave is seeking a talented Content Writer to create engaging content for our clients. You will be responsible for writing blog posts, articles, and marketing copy that resonates with our target audience. The ideal candidate should have a strong writing portfolio and experience in content creation.",
        "experience": "2 years in content writing",
        "application_link": "https://mediawave.com.au/apply/content-writer",
        "location": "nsw-newcastle",
        "job_type": "freelance"
    },
    {
        "title": "Digital Marketing Specialist",
        "salary": 75000,
        "department": "marketing",
        "role_description": "MediaWave is looking for a Digital Marketing Specialist to join our team and drive our online marketing efforts. You will be responsible for managing SEO, PPC, and email marketing campaigns. Experience with Google Analytics and SEMrush is essential.",
        "experience": "3 years in digital marketing",
        "application_link": "https://mediawave.com.au/apply/digital-marketing-specialist",
        "location": "vic-melbourne",
        "job_type": "full-time"
    },
    {
        "title": "Chief Technology Officer (CTO)",
        "salary": 160000,
        "department": "co-founder",
        "role_description": "CloudCore Technologies is seeking a Chief Technology Officer (CTO) to join our leadership team. As CTO, you will be responsible for setting the technological direction of the company and leading our development teams. The ideal candidate should have extensive experience in cloud computing and a track record of successful technology leadership.",
        "experience": "10 years in technology leadership",
        "application_link": "https://cloudcoretech.com.au/apply/cto",
        "location": "wa-perth",
        "job_type": "full-time",
        "closing_date": "2024-10-31"
    },
    {
        "title": "Cloud Engineer",
        "salary": 130000,
        "department": "technology",
        "role_description": "CloudCore Technologies is looking for a Cloud Engineer to help design, implement, and maintain our cloud infrastructure. You will work with cutting-edge technologies such as AWS, Azure, and Kubernetes to ensure our systems are scalable, secure, and reliable. Proficiency in cloud architecture and automation tools is required.",
        "experience": "5 years in cloud engineering",
        "application_link": "Email careers@cloudcoretech.com.au",
        "location": "remote",
        "job_type": "full-time"
    },
    {
        "title": "DevOps Engineer",
        "salary": 125000,
        "department": "technology",
        "role_description": "CloudCore Technologies is hiring a DevOps Engineer to optimize our CI/CD pipelines and improve our deployment processes. You will work closely with our development and operations teams to automate workflows and ensure smooth releases. Experience with Jenkins, Docker, and Terraform is essential.",
        "experience": "3 years in DevOps",
        "application_link": "https://cloudcoretech.com.au/apply/devops-engineer",
        "location": "nsw-sydney",
        "job_type": "full-time"
    },
    {
        "title": "Network Administrator",
        "salary": 95000,
        "department": "technology",
        "role_description": "CloudCore Technologies is seeking a Network Administrator to manage our internal and external networks. In this role, you will be responsible for monitoring network performance, troubleshooting issues, and ensuring network security. The ideal candidate should have experience with network hardware and software, as well as a strong understanding of cybersecurity principles.",
        "experience": "4 years in network administration",
        "application_link": "Email hr@cloudcoretech.com.au",
        "location": "qld",
        "location-specific": "townsville",
        "job_type": "full-time"
    },
    {
        "title": "Chief Financial Officer (CFO)",
        "salary": 150000,
        "department": "finance",
        "role_description": "MediFlow is seeking a Chief Financial Officer (CFO) to join our executive team. As CFO, you will be responsible for overseeing our financial strategy, managing budgets, and ensuring the financial health of the company. The ideal candidate should have extensive experience in financial management and a background in the healthcare industry.",
        "experience": "8 years in finance leadership",
        "application_link": "https://mediflow.com.au/apply/cfo",
        "location": "vic-melbourne",
        "job_type": "full-time",
        "closing_date": "2024-11-15"
    },
    {
        "title": "Full Stack Developer",
        "salary": 125000,
        "department": "technology",
        "role_description": "MediFlow is hiring a Full Stack Developer to work on our healthcare management platform. You will be responsible for developing new features and ensuring the platform runs smoothly. Proficiency in JavaScript (React/Node.js) and experience with database management systems like MySQL or MongoDB is required.",
        "experience": "4 years in full-stack development",
        "application_link": "https://mediflow.com.au/apply/full-stack-developer",
        "location": "sa-adelaide",
        "job_type": "full-time"
    },
    {
        "title": "Healthcare Analyst",
        "salary": 90000,
        "department": "technology",
        "role_description": "MediFlow is seeking a Healthcare Analyst to analyze healthcare data and provide actionable insights. You will work closely with our data science and product teams to optimize healthcare outcomes for our clients. Experience with healthcare analytics tools and a strong understanding of healthcare regulations are essential.",
        "experience": "3 years in healthcare analytics",
        "application_link": "Email hr@mediflow.com.au",
        "location": "qld",
        "location-specific": "cairns",
        "job_type": "full-time"
    },
    {
        "title": "Project Manager",
        "salary": 110000,
        "department": "operations",
        "role_description": "SolarBright is looking for an experienced Project Manager to lead our renewable energy projects. You will be responsible for overseeing project timelines, managing budgets, and ensuring successful project delivery. Experience with solar energy projects and a background in engineering are highly preferred.",
        "experience": "5 years in project management",
        "application_link": "https://solarbright.com.au/apply/project-manager",
        "location": "nt",
        "location-specific": "darwin",
        "job_type": "full-time"
    },
    {
        "title": "Electrical Engineer",
        "salary": 95000,
        "department": "technology",
        "role_description": "SolarBright is seeking an Electrical Engineer to design and implement electrical systems for our solar energy projects. You will work closely with our project managers to ensure all electrical components are installed safely and efficiently. The ideal candidate should have experience with solar energy systems and be proficient in AutoCAD.",
        "experience": "4 years in electrical engineering",
        "application_link": "Email careers@solarbright.com.au",
        "location": "wa",
        "location-specific": "broome",
        "job_type": "full-time"
    },
    {
        "title": "Sales Manager",
        "salary": 85000,
        "department": "marketing",
        "role_description": "SolarBright is hiring a Sales Manager to drive our sales efforts in the renewable energy sector. You will be responsible for developing sales strategies, managing client relationships, and achieving sales targets. The ideal candidate should have experience in sales management and a passion for renewable energy.",
        "experience": "3 years in sales management",
        "application_link": "https://solarbright.com.au/apply/sales-manager",
        "location": "nsw-newcastle",
        "job_type": "full-time"
    },
    {
        "title": "Data Engineer",
        "salary": 120000,
        "department": "technology",
        "role_description": "AgriData Insights is looking for a Data Engineer to manage and optimize our data pipelines. You will be responsible for ensuring data quality and availability, building data models, and working closely with our data science team. Proficiency in Python and SQL is required, and experience with big data technologies like Hadoop or Spark is a plus.",
        "experience": "4 years in data engineering",
        "application_link": "https://agridatainsights.com.au/apply/data-engineer",
        "location": "remote",
        "job_type": "full-time",
        "closing_date": "2024-12-01"
    },
    {
        "title": "Agricultural Scientist",
        "salary": 95000,
        "department": "operations",
        "role_description": "AgriData Insights is seeking an Agricultural Scientist to analyze data and provide insights into crop health, soil conditions, and other key factors in agriculture. You will work closely with our data engineers and farmers to implement data-driven solutions that improve crop yields and sustainability.",
        "experience": "3 years in agricultural science",
        "application_link": "Email hr@agridatainsights.com.au",
        "location": "tas",
        "location-specific": "launceston",
        "job_type": "full-time"
    },
    {
        "title": "Marketing Manager",
        "salary": 90000,
        "department": "marketing",
        "role_description": "AgriData Insights is hiring a Marketing Manager to lead our marketing efforts and increase brand visibility. You will be responsible for developing marketing strategies, managing campaigns, and analyzing their effectiveness. Experience with digital marketing tools and a background in agriculture are highly preferred.",
        "experience": "4 years in marketing",
        "application_link": "https://agridatainsights.com.au/apply/marketing-manager",
        "location": "vic",
        "location-specific": "bendigo",
        "job_type": "full-time"
    }
]


