"""Update Job model for location

Revision ID: 770878e28682
Revises: 2cd6506e743a
Create Date: 2024-08-24 18:03:16.221470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770878e28682'
down_revision = '2cd6506e743a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postcode', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('postcode')

    # ### end Alembic commands ###
