"""Update Job model with additional detail

Revision ID: b0cd6f933466
Revises: 3586ff81d60f
Create Date: 2024-08-24 14:18:31.551043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cd6f933466'
down_revision = '3586ff81d60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essential_experience', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('optional_experience', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('key_responsibility_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('key_responsibility_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('key_responsibility_3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('key_responsibility_4', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('key_responsibility_5', sa.String(), nullable=True))
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('key_responsibility_5')
        batch_op.drop_column('key_responsibility_4')
        batch_op.drop_column('key_responsibility_3')
        batch_op.drop_column('key_responsibility_2')
        batch_op.drop_column('key_responsibility_1')
        batch_op.drop_column('optional_experience')
        batch_op.drop_column('essential_experience')

    # ### end Alembic commands ###
