"""Add archived_job to Job d model

Revision ID: cd891e6dcac4
Revises: 770878e28682
Create Date: 2024-08-29 00:56:47.422965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd891e6dcac4'
down_revision = '770878e28682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_job', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('archived_job')

    # ### end Alembic commands ###
